apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: planka
  namespace: planka
spec:
  interval: 1m0s
  url: http://plankanban.github.io/planka
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: planka
  namespace: planka
spec:
  chart:
    spec:
      chart: planka
      sourceRef:
        kind: HelmRepository
        name: planka
      version: '*'
  interval: 1m0s
  values:
    secretkey: "8215c330360e427326a0c52d6d931fac68d4610a6f8895b0a85aaf402e3a86d74027f02731714fec4bbcbaf07faa1b7e1f622a4c01b60c08894b7ff1ff8e8337"
    
    admin_email: "admin@env.admin"
    admin_password: "pas$!23"
    admin_name: "admin"
    admin_username: "plankaeb"
    
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
      hosts:
        - host: planka.k8s-01.idi.nahui
          paths:
            - path: /
              pathType: ImplementationSpecific
    
      tls:
        - secretName: planka-tls
          hosts:
            - planka.k8s-01.idi.nahui
    
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 10Gi
        mountPath: /storage
    
    env:
      OIDC_ISSUER: https://auth.k8s-01.idi.nahui/application/o/planka/
      OIDC_CLIENT_ID: UL77Nh2Dnlw5aumJsFJt3igRbM6ke8AYMFkYwkBz
      OIDC_CLIENT_SECRET: ILh7CSw8cAjjGh3DD4O2gOYvFCahzNcszqnPP27CUFMMxfyF4MByRsrhpIWpoFAStau3m7730hlR4sLs2cJpIjq7E8bi4LCGPMIOXrC4tdJmvahBtOeSYnSHUxocwes5
      OIDC_ENFORCED: "true"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      OIDC_ADMIN_ROLES: planka_admin
    
