apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: planka
  namespace: planka
spec:
  interval: 1m0s
  url: http://plankanban.github.io/planka
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: planka
  namespace: planka
spec:
  chart:
    spec:
      chart: planka
      sourceRef:
        kind: HelmRepository
        name: planka
      version: '*'
  interval: 1m0s
