apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 10m
  releaseName: authentik

  chart:
    spec:
      chart: ./claster/authentik/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m

  install:
    createNamespace: false
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  valuesFrom:
    - kind: ConfigMap
      name: authentik-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: authentik-no-tls
      valuesKey: values.yaml
