apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 10m
  path: ./authenik/flux
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: k8s-01
